In [96]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch.nn as nn
torch.__version__

'2.1.2+cpu'

In [97]:
#scaler is used to represent one-D the data to 0-1
scaler= torch.tensor(255.0)
scaler


tensor(255.)

In [98]:
#vector represent 2D
vector=torch.tensor([2,3])

In [99]:
vector


tensor([2, 3])

In [100]:
vector.shape

torch.Size([2])

In [101]:
vector.fill_(0.0)

tensor([0, 0])

In [102]:
vector

tensor([0, 0])

In [103]:
MATRIX=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [104]:
MATRIX[0]

tensor([1, 2, 3])

In [105]:
MATRIX.shape

torch.Size([3, 3])

In [106]:
TENSOR=torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [107]:
TENSOR.size()

torch.Size([2, 3, 3])

In [108]:
TENSOR.ndim

3

In [109]:
rand_tensor=torch.rand(3,3)
rand_tensor

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411]])

In [110]:
rand_tensor.dtype

torch.float32

In [111]:
rand_tensor.ndim

2

In [112]:
rand_image_tensor=torch.rand(3,224,224)
rand_tensor

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411]])

In [113]:
zeros_tensor=torch.zeros(3,3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [114]:
y=rand_tensor*zeros_tensor
y

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [115]:
#range tensor
range_tensor=torch.arange(0,10)
range_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
#arange tensor
arange_tensor=torch.arange(0,10,2)
arange_tensor

tensor([0, 2, 4, 6, 8])

In [117]:
#Float 32 tensor
#device shows either cpu orgpu will run the tensor
float_tensor=torch.tensor([1,2,3,4],dtype=None,device=None,requires_grad=False)
float_tensor

tensor([1, 2, 3, 4])

In [118]:
float_tensor.dtype

torch.int64

In [119]:
float_tensor.device

device(type='cpu')

In [120]:
#perform addition,subtraction,multiplication,division, and matrix multiplication
x=torch.tensor([1,2,3])
y=torch.tensor([9,8,7])
x+y

x-y

x*y

x/y

x=torch.arange(0,9).reshape(3,3)
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [121]:
y=torch.arange(0,9).reshape(3,3)
x*y

tensor([[ 0,  1,  4],
        [ 9, 16, 25],
        [36, 49, 64]])

In [122]:
#element wise multiplication
x=torch.tensor([1,2,3])
y=torch.tensor([9,8,7])
x*y

#dot product
x=torch.tensor([1,2,3])
y=torch.tensor([9,8,7])
torch.dot(x,y)


tensor(46)

In [123]:
%%time
torch.matmul(x,y)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(46)

In [124]:
#2D matrix multiplication
x=torch.arange(0,9).reshape(3,3)
y=torch.arange(0,9).reshape(3,3)
torch.matmul(x,y)


tensor([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [125]:
#Finding min,max,mean,standard deviation, and sum of tensor
x=torch.arange(0,9).reshape(3,3)
x

x.min()

x.max()

# x.mean()

# x.std()

x.sum()



tensor(36)

In [126]:
#positional and label based indexing
x=torch.arange(0,9).reshape(3,3)
x

x.argmax()

tensor(8)

In [127]:
x.argmin()

tensor(0)

In [128]:
#stacking,concatenating,splitting,chunking,reshaping and squeezing tensors
x=torch.arange(0,9).reshape(3,3)
x

y=torch.arange(10,19).reshape(3,3)

y

torch.cat((x,y),dim=0)


tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

In [129]:
x=torch.arange(0.,10.)
x.shape, x

(torch.Size([10]), tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [130]:
#reshape first element shows rows
x_reshaped=x.reshape(1,10)

x_reshaped.shape, x_reshaped

(torch.Size([1, 10]), tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [131]:
#view is same as reshape, share the same memory

x_view=x.view(2,5)

x_view.shape, x_view

(torch.Size([2, 5]),
 tensor([[0., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]))

In [132]:
x_view[0,0]=100
x,x_view

(tensor([100.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.]),
 tensor([[100.,   1.,   2.,   3.,   4.],
         [  5.,   6.,   7.,   8.,   9.]]))

In [133]:
#trying stacking on x
x=torch.arange(0,9).reshape(3,3)

print(x)

y=torch.arange(10,19).reshape(3,3)

print(y)

torch.stack((x,y),dim=0).shape

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])


torch.Size([2, 3, 3])

In [134]:
#trying squeeze and unsqueeze on x tensor (squeeze removes the dimension of 1 and unsqueeze adds the dimension of 1) where 1 means bracket
x=torch.arange(0,9).reshape(3,3)

print(x)

x.unsqueeze(dim=0).shape

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


torch.Size([1, 3, 3])

In [135]:
x.unsqueeze(dim=0).shape

torch.Size([1, 3, 3])

In [136]:
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [137]:
#trying permute method on x tensor replaces values with repect to indexes
x=torch.arange(0,9).reshape(3,3)

print(x)

x.permute(1,0)



tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])

In [138]:
n=np.arange(0.,9.0)
n.dtype

dtype('float64')

In [139]:
tensor=torch.from_numpy(n).type(torch.float16)
tensor

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float16)

In [140]:
#back to numpy array from tensor
tensor.numpy()

array([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=float16)

In [141]:
#Reproducibility (trying to take random out of random)

torch.manual_seed(42)
t=torch.rand(2,3)

torch.manual_seed(42)
t1=torch.rand(2,3)

In [142]:
#creating classification model with pytorch on iris data set
#we have two hidden layers in neural network
#input layer has 4 neurons as it has four features
#relu is used as activation function in hidden layers if value is less than 0 it will be 0 and if value is greater than 0 it will be same

class Iris_Model(nn.Module):
    def __init__(self,in_features=4,h1=8,h2=9,out_features=3):
        super().__init__()
        self.fc1=nn.Linear(in_features,h1)
        self.fc2=nn.Linear(h1,h2)
        self.out=nn.Linear(h2,out_features)
    def forward(self,x):
        x=F.relu(self.fc1(x))
        x=F.relu(self.fc2(x))
        x=self.out(x)
        return x

torch.manual_seed(32)
model=Iris_Model()
model



Iris_Model(
  (fc1): Linear(in_features=4, out_features=8, bias=True)
  (fc2): Linear(in_features=8, out_features=9, bias=True)
  (out): Linear(in_features=9, out_features=3, bias=True)
)